# Configuring pandas

In [ ]:
# import numpy and pandas
import numpy as np
import pandas as pd

# used for dates
import datetime
from datetime import datetime, date


# bring in matplotlib for graphics
import matplotlib.pyplot as plt
%matplotlib inline

# Creating a DataFrame from a CSV file

In [ ]:
# read in the data and print the first five rows
# use the Symbol column as the index, and
# only read in columns in positions 0, 2, 3, 7
nifty50 = pd.read_csv("sample_data/nifty50.csv")

                                     #usecols=[0, 2, 3, 7]

In [ ]:
# peek at the first 5 rows of the data using .head()
nifty50.head()

,SYMBOL \n,OPEN \n,HIGH \n,LOW \n,PREV. CLOSE \n,LTP \n,INDICATIVE CLOSE \n,CHNG \n,%CHNG \n,VOLUME \n(shares),VALUE \n (₹ Crores),52W H \n,52W L \n,30 D %CHNG \n,365 D % CHNG \n 02-Aug-2024
0,NIFTY 50,"24,720.25","24,733.10","24,590.30","24,722.75","24,649.55",-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
1,TITAN,"3,356.30","3,443.00","3,348.00","3,356.30","3,424.00",-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28
2,INDUSINDBK,820.00,848.70,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67
3,SBILIFE,"1,833.30","1,860.40","1,818.70","1,831.50","1,860.00",-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42
4,MARUTI,"12,400.00","12,577.00","12,370.00","12,365.00","12,543.00",-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49

In [ ]:
nifty50.dtypes

SYMBOL \n                       object
OPEN \n                         object
HIGH \n                         object
LOW \n                          object
PREV. CLOSE \n                  object
LTP \n                          object
INDICATIVE CLOSE \n             object
CHNG \n                        float64
%CHNG \n                       float64
VOLUME \n(shares)               object
VALUE \n (₹ Crores)             object
52W H \n                        object
52W L \n                        object
30 D   %CHNG \n                float64
365 D % CHNG \n 02-Aug-2024     object
dtype: object

In [ ]:
# how many rows of data?  Should be 500
len(nifty50)

51

In [ ]:
# what is the shape?
nifty50.shape

(51, 15)

In [ ]:
# what is the size?
nifty50.size

765

In [ ]:
# examine the index
nifty50.index

RangeIndex(start=0, stop=51, step=1)

In [ ]:
# get the columns
nifty50.columns

Index(['SYMBOL \n', 'OPEN \n', 'HIGH \n', 'LOW \n', 'PREV. CLOSE \n', 'LTP \n',
       'INDICATIVE CLOSE \n', 'CHNG \n', '%CHNG \n', 'VOLUME \n(shares)',
       'VALUE \n (₹ Crores)', '52W H \n', '52W L \n', '30 D   %CHNG \n',
       '365 D % CHNG \n 02-Aug-2024'],
      dtype='object')

In [ ]:
#Fix the names of the columns
col_names={col_name:col_name.replace("\n","").strip().title().split('(')[0].strip() for col_name in nifty50.columns}
print(col_names)
nifty50=nifty50.rename(columns=col_names)
nifty50.head()
print(nifty50.columns)

{'Symbol': 'Symbol', 'Open': 'Open', 'High': 'High', 'Low': 'Low', 'Prev. Close': 'Prev. Close', 'Ltp': 'Ltp', 'Indicative Close': 'Indicative Close', 'Chng': 'Chng', '%Chng': '%Chng', 'Volume ': 'Volume', 'Value  ': 'Value', '52W H': '52W H', '52W L': '52W L', '30 D   %Chng': '30 D   %Chng', '365 D % Chng  02-Aug-2024': '365 D % Chng  02-Aug-2024'}
Index(['Symbol', 'Open', 'High', 'Low', 'Prev. Close', 'Ltp',
       'Indicative Close', 'Chng', '%Chng', 'Volume', 'Value', '52W H',
       '52W L', '30 D   %Chng', '365 D % Chng  02-Aug-2024'],
      dtype='object')

In [ ]:
print(col_names)

{'SYMBOL \n': 'Symbol', 'OPEN \n': 'Open', 'HIGH \n': 'High', 'LOW \n': 'Low', 'PREV. CLOSE \n': 'Prev. Close', 'LTP \n': 'Ltp', 'INDICATIVE CLOSE \n': 'Indicative Close', 'CHNG \n': 'Chng', '%CHNG \n': '%Chng', 'VOLUME \n(shares)': 'Volume ', 'VALUE \n (₹ Crores)': 'Value  ', '52W H \n': '52W H', '52W L \n': '52W L', '30 D   %CHNG \n': '30 D   %Chng', '365 D % CHNG \n 02-Aug-2024': '365 D % Chng  02-Aug-2024'}

In [ ]:
# retrieve the Sector column
nifty50.head()

,Symbol,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
0,NIFTY 50,"24,720.25","24,733.10","24,590.30","24,722.75","24,649.55",-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
1,TITAN,"3,356.30","3,443.00","3,348.00","3,356.30","3,424.00",-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28
2,INDUSINDBK,820.00,848.70,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67
3,SBILIFE,"1,833.30","1,860.40","1,818.70","1,831.50","1,860.00",-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42
4,MARUTI,"12,400.00","12,577.00","12,370.00","12,365.00","12,543.00",-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49

In [ ]:
clean_cols=['Open', 'High', 'Low', 'Prev. Close','Ltp']
for col in clean_cols:
    try:
        nifty50[col]=nifty50[col].str.replace(",","").astype(float)#pd.to_numeric
    except:
        continue
print(nifty50.dtypes)
print(nifty50.head())

Symbol                        object
Open                         float64
High                         float64
Low                          float64
Prev. Close                  float64
Ltp                          float64
Indicative Close              object
Chng                         float64
%Chng                        float64
Volume                        object
Value                         object
52W H                         object
52W L                         object
30 D   %Chng                 float64
365 D % Chng  02-Aug-2024     object
dtype: object
       Symbol      Open     High       Low  Prev. Close       Ltp  \
0    NIFTY 50  24720.25  24733.1  24590.30     24722.75  24649.55
1       TITAN   3356.30   3443.0   3348.00      3356.30   3424.00
2  INDUSINDBK    820.00    848.7    810.05       804.05    817.40
3     SBILIFE   1833.30   1860.4   1818.70      1831.50   1860.00
4      MARUTI  12400.00  12577.0  12370.00     12365.00  12543.00

  Indicative Close    Chng  %Chng       Volume     Value        52W H  \
0                -  -73.20  -0.30  25,18,49,778  23,815.20  26,277.35
1                -   67.70   2.02      8,37,335     285.13   3,867.00
2                -   13.35   1.66   1,89,82,770   1,570.06   1,498.00
3                -   28.50   1.56     12,51,783     231.37   1,936.00
4                -  178.00   1.44      2,33,560     292.25  13,541.65

       52W L  30 D   %Chng 365 D % Chng  02-Aug-2024
0  21,743.65         -3.19                     -0.28
1   2,925.00         -7.29                     -1.28
2     606.00         -4.33                    -41.67
3   1,372.55          3.18                      6.42
4  10,725.00         -0.86                     -1.49

In [ ]:
nifty50['Ltp'].astype(float)

0     24649.55
1      3424.00
2       817.40
3      1860.00
4     12543.00
5       379.80
6      5320.00
7      5684.00
8      1930.30
9       892.30
10      629.00
11      800.50
12    12327.00
13     1483.00
14     3650.00
15      333.65
16     1480.90
17     1942.00
18     8221.00
19     3213.00
20     2004.00
21     1071.10
22      655.00
23     2792.70
24     4540.00
25      159.45
26     1054.10
27      234.30
28      245.45
29      685.85
30      737.65
31      332.60
32     2532.40
33     3060.00
34     1981.00
35     2264.20
36     1631.90
37     2434.90
38     7260.00
39     1065.50
40      285.90
41      413.80
42      386.60
43     1214.40
44      301.95
45     1445.00
46     1496.30
47     2333.00
48     1460.00
49     1390.00
50     1361.90
Name: Ltp, dtype: float64

In [ ]:
type(nifty50['Ltp'])

pandas.core.series.Series

In [ ]:
# retrieve the Open and Close Value columns
nifty50[['Open', 'High']].head()

       Open     High
0  24720.25  24733.1
1   3356.30   3443.0
2    820.00    848.7
3   1833.30   1860.4
4  12400.00  12577.0

In [ ]:
# show that this is a DataFrame
type(nifty50[['Open', 'High']])

pandas.core.frame.DataFrame

In [ ]:
# attribute access of column by name
nifty50.Open

0     24720.25
1      3356.30
2       820.00
3      1833.30
4     12400.00
5       376.00
6      5245.00
7      5625.00
8      1920.00
9       889.00
10      630.50
11      798.00
12    12330.00
13     1470.10
14     3630.00
15      332.45
16     1479.90
17     1930.10
18     8176.00
19     3195.00
20     2008.00
21     1068.00
22      655.95
23     2799.00
24     4536.00
25      159.56
26     1059.00
27      235.50
28      246.05
29      692.00
30      735.80
31      334.45
32     2537.50
33     3074.40
34     1986.50
35     2279.70
36     1640.90
37     2461.90
38     7312.00
39     1072.60
40      287.10
41      417.20
42      390.00
43     1225.00
44      306.90
45     1453.00
46     1513.50
47     2370.00
48     1478.70
49     1411.00
50     1392.00
Name: Open, dtype: float64

In [ ]:
nifty50.head()

,Symbol,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
0,NIFTY 50,24720.25,24733.1,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
1,TITAN,3356.30,3443.0,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28
2,INDUSINDBK,820.00,848.7,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67
3,SBILIFE,1833.30,1860.4,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42
4,MARUTI,12400.00,12577.0,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49

In [ ]:
nifty50=nifty50.set_index('Symbol')

In [ ]:
nifty50.head()

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
NIFTY 50,24720.25,24733.1,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
TITAN,3356.30,3443.0,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28
INDUSINDBK,820.00,848.7,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67
SBILIFE,1833.30,1860.4,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42
MARUTI,12400.00,12577.0,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49

# Selecting rows of a DataFrame

In [ ]:
# get row with label MMM
# returned as a Series
nifty50.loc['INFY']

Open                              1478.7
High                              1478.7
Low                               1455.0
Prev. Close                       1480.5
Ltp                               1460.0
Indicative Close                       -
Chng                               -20.5
%Chng                              -1.38
Volume                       1,02,13,323
Value                           1,492.22
52W H                           2,006.45
52W L                           1,307.00
30 D   %Chng                       -11.0
365 D % Chng  02-Aug-2024         -19.82
Name: INFY, dtype: object

In [ ]:
# rows with label MMM and MSFT
# this is a DataFrame result
nifty50.loc[['INFY', 'TCS']]

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
INFY,1478.7,1478.7,1455.0,1480.5,1460.0,-,-20.5,-1.38,"1,02,13,323","1,492.22","2,006.45","1,307.00",-11.00,-19.82
TCS,3074.4,3077.5,3042.0,3074.4,3060.0,-,-14.4,-0.47,"19,27,996",589.57,"4,592.25","2,991.60",-10.41,-28.46

In [ ]:
nifty50.loc['INFY','Ltp']

np.float64(1460.0)

In [ ]:
# get rows in location 0 and 2
nifty50.iloc[[0, 2]]

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
NIFTY 50,24720.25,24733.1,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
INDUSINDBK,820.00,848.7,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67

In [ ]:
# get the location of MMM and A in the index
i1 = nifty50.index.get_loc('INFY')
i2 = nifty50.index.get_loc('TCS')
(i1, i2)

(48, 33)

In [ ]:
nifty50.iloc[i2:i1]

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
TCS,3074.4,3077.50,3042.00,3074.40,3060.00,-,-14.40,-0.47,"19,27,996",589.57,"4,592.25","2,991.60",-10.41,-28.46
HDFCBANK,1986.5,1994.40,1965.50,1992.00,1981.00,-,-11.00,-0.55,"1,19,89,029","2,368.55","2,037.70","1,593.30",-0.59,19.19
NESTLEIND,2279.7,2282.40,2250.10,2277.40,2264.20,-,-13.20,-0.58,"5,67,967",128.49,"2,778.00","2,110.00",-5.24,-9.13
SUNPHARMA,1640.9,1644.60,1620.10,1641.60,1631.90,-,-9.70,-0.59,"16,22,897",264.48,"1,960.35","1,553.05",-2.64,-5.75
ASIANPAINT,2461.9,2463.70,2409.10,2449.80,2434.90,-,-14.90,-0.61,"6,59,094",160.35,"3,394.90","2,124.75",0.52,-21.56
APOLLOHOSP,7312.0,7342.00,7235.50,7308.00,7260.00,-,-48.00,-0.66,"2,82,791",205.90,"7,635.00","6,001.00",-3.70,8.40
TATACONSUM,1072.6,1073.00,1059.10,1072.60,1065.50,-,-7.10,-0.66,"8,61,402",91.65,"1,234.30",882.90,-2.30,-10.81
POWERGRID,287.1,288.65,285.10,287.95,285.90,-,-2.05,-0.71,"1,55,61,914",445.79,366.25,247.30,-2.72,-20.17
ITC,417.2,417.95,413.00,416.85,413.80,-,-3.05,-0.73,"84,95,104",351.98,528.50,390.15,0.39,-15.32
BEL,390.0,390.25,383.35,389.55,386.60,-,-2.95,-0.76,"1,34,82,710",520.50,436.00,240.25,-9.57,27.63
DRREDDY,1225.0,1232.00,1205.00,1225.00,1214.40,-,-10.60,-0.87,"9,56,582",116.23,"1,421.49","1,020.00",-7.08,-82.56
ETERNAL,306.9,307.60,301.70,305.25,301.95,-,-3.30,-1.08,"1,48,20,256",449.69,314.45,194.80,15.59,-
ICICIBANK,1453.0,1461.50,1441.00,1463.20,1445.00,-,-18.20,-1.24,"1,47,99,343","2,139.63","1,500.00","1,153.00",0.11,20.71
CIPLA,1513.5,1517.30,1491.10,1515.10,1496.30,-,-18.80,-1.24,"11,56,528",173.61,"1,702.05","1,335.00",-0.89,-1.90
ADANIENT,2370.0,2370.00,2316.00,2363.60,2333.00,-,-30.60,-1.29,"5,76,742",134.58,"3,242.65","2,025.00",-10.42,-26.34

In [ ]:
# and get the rows
nifty50.iloc[[i1,i2]]

# Scalar lookup by label or location using .at[] and .iat[]

In [ ]:
# by label in both the index and column
nifty50.at['INFY', 'Ltp']

In [ ]:
# by location.  Row 0, column 1
nifty50.iat[0, 1]

In [ ]:
nifty50.at['INFY','Open']

# Adding new columns with [] and .insert()

In [ ]:
# make a copy so that we keep the original data unchanged
nifty50_copy = nifty50.copy()
# add the new column
nifty50_copy['RoundedPrice'] = nifty50['Ltp'].round()
nifty50_copy[:2]

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024,RoundedPrice
Symbol,,,,,,,,,,,,,,,
NIFTY 50,24720.25,24733.1,24590.3,24722.75,24649.55,-,-73.2,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28,24650.0
TITAN,3356.30,3443.0,3348.0,3356.30,3424.00,-,67.7,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28,3424.0

In [ ]:
# make a copy so that we keep the original data unchanged
copy = nifty50.copy()
# insert sp500.Price * 2 as the
# second column in the DataFrame
copy.insert(1, 'RoundedPrice', nifty50.Ltp.round())
copy[:2]

,Open,RoundedPrice,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,,
NIFTY 50,24720.25,24650.0,24733.1,24590.3,24722.75,24649.55,-,-73.2,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
TITAN,3356.30,3424.0,3443.0,3348.0,3356.30,3424.00,-,67.7,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28

# Adding columns through enlargement

In [ ]:
# copy of subset / slice
ss = nifty50[:3].copy()
# add the new column initialized to 0
ss.loc[:,'PER'] = 0
# take a look at the results
ss

In [ ]:
# copy of subset / slice
ss = nifty50[:3].copy()
# add the new column initialized with random numbers
np.random.seed(123456)
ss.loc[:,'PER'] = pd.Series(np.random.normal(size=3), index=ss.index)
# take a look at the results
ss

# Adding columns using concatenation

In [ ]:
# create a DataFrame with only the RoundedPrice column
rounded_price = pd.DataFrame({'RoundedPrice':
                              nifty50.Ltp.round()})
# concatenate along the columns axis
concatenated = pd.concat([nifty50, rounded_price], axis=1)
concatenated[:5]

In [ ]:
# create a DataFrame with only the RoundedPrice column
rounded_price = pd.DataFrame({'Price': nifty50.Ltp.round()})
rounded_price[:5]

# Reordering columns

In [ ]:
# return a new DataFrame with the columns reversed
reversed_column_names = nifty50.columns[::-1]
nifty50[reversed_column_names][:5]

,365 D % Chng 02-Aug-2024,30 D %Chng,52W L,52W H,Value,Volume,%Chng,Chng,Indicative Close,Ltp,Prev. Close,Low,High,Open
Symbol,,,,,,,,,,,,,,
NIFTY 50,-0.28,-3.19,"21,743.65","26,277.35","23,815.20","25,18,49,778",-0.30,-73.20,-,24649.55,24722.75,24590.30,24733.1,24720.25
TITAN,-1.28,-7.29,"2,925.00","3,867.00",285.13,"8,37,335",2.02,67.70,-,3424.00,3356.30,3348.00,3443.0,3356.30
INDUSINDBK,-41.67,-4.33,606.00,"1,498.00","1,570.06","1,89,82,770",1.66,13.35,-,817.40,804.05,810.05,848.7,820.00
SBILIFE,6.42,3.18,"1,372.55","1,936.00",231.37,"12,51,783",1.56,28.50,-,1860.00,1831.50,1818.70,1860.4,1833.30
MARUTI,-1.49,-0.86,"10,725.00","13,541.65",292.25,"2,33,560",1.44,178.00,-,12543.00,12365.00,12370.00,12577.0,12400.00

# Deleting columns

In [ ]:
nifty50.columns

In [ ]:
# Example of using del to delete a column
# make a copy as this is done in-place
copy = nifty50.copy()
del copy['Prev. Close']
copy[:2]

In [ ]:
copy.head()

In [ ]:
# Example of using pop to remove a column from a DataFrame
# first make a copy of a subset of the data frame as
# pop works in place
# this will remove Volume and return it as a series
print(copy.columns)
popped = copy.pop('Volume ')
# Volume column removed in-place
copy[:2]

In [ ]:
# and we have the Volume column as the result of the pop
popped[:5]

In [ ]:
# Example of using drop to remove a column
# this will return a new DataFrame with 'Open removed
# the copy DataFrame is not modified
afterdrop = copy.drop(['Open'], axis = 1)
afterdrop[:5]

# Concatenating rows

In [ ]:
# copy the first three rows of sp500
df1 = nifty50.iloc[0:3].copy()
# copy 10th and 11th rows
df2 = nifty50.iloc[[10, 11, 2]]
# pass them as a list
pd.concat([df1, df2])

# Adding and replacing rows via setting with enlargement

In [ ]:
# get a small subset of the nifty50
# make sure to copy the slice to make a copy
ss = nifty50[:3].copy()
# create a new row with index label FOO
# and assign some values to the columns via a list
ss['FOO'] = ['the sector', 100, 110]
ss

# Removing rows using .drop()

In [ ]:
# drop rows with labels ABT and ACN
afterdrop = ss.drop(['TITAN'])
afterdrop[:5]

# Removing rows using Boolean selection

In [ ]:
# determine the rows where Price > 300
selection = nifty50.Ltp > 300
# report number of rows and number that will be dropped
(len(selection), selection.sum())

In [ ]:
# select the complement of the expression
# note the use of the complement of the selection
price_less_than_300 = nifty50[~selection]
price_less_than_300

In [ ]:
price_less_than_300=nifty50[nifty50['Ltp']<300]
price_less_than_300

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
TATASTEEL,159.56,160.14,158.28,159.56,159.45,-,-0.11,-0.07,"1,44,41,034",230.16,170.18,122.62,-2.08,0.88
ONGC,235.50,236.00,233.05,234.83,234.30,-,-0.53,-0.23,"95,62,689",224.06,345.00,205.00,-4.39,-28.97
WIPRO,246.05,246.95,244.53,246.05,245.45,-,-0.60,-0.24,"73,83,968",181.33,324.60,228.00,-8.94,-51.03
POWERGRID,287.10,288.65,285.10,287.95,285.90,-,-2.05,-0.71,"1,55,61,914",445.79,366.25,247.30,-2.72,-20.17

In [ ]:
nifty50.head()

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
NIFTY 50,24720.25,24733.1,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
TITAN,3356.30,3443.0,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28
INDUSINDBK,820.00,848.7,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67
SBILIFE,1833.30,1860.4,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42
MARUTI,12400.00,12577.0,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49

# Join and Merge

In [ ]:
nifty_sector=pd.read_csv("sample_data/ind_nifty50list.csv")

In [ ]:
nifty_sector.head()

,Company Name,Industry,Symbol,Series,ISIN Code
0,Adani Enterprises Ltd.,Metals & Mining,ADANIENT,EQ,INE423A01024
1,Adani Ports and Special Economic Zone Ltd.,Services,ADANIPORTS,EQ,INE742F01042
2,Apollo Hospitals Enterprise Ltd.,Healthcare,APOLLOHOSP,EQ,INE437A01024
3,Asian Paints Ltd.,Consumer Durables,ASIANPAINT,EQ,INE021A01026
4,Axis Bank Ltd.,Financial Services,AXISBANK,EQ,INE238A01034

In [ ]:
nifty50.head()

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
NIFTY 50,24720.25,24733.1,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
TITAN,3356.30,3443.0,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28
INDUSINDBK,820.00,848.7,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67
SBILIFE,1833.30,1860.4,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42
MARUTI,12400.00,12577.0,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49

In [ ]:
nifty_merge = nifty50.merge(nifty_sector,right_on='Symbol',how='inner',left_on='Symbol') #standard merge

In [ ]:
nifty_merge

,Symbol,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024,Company Name,Industry,Series,ISIN Code
0,TITAN,3356.30,3443.00,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28,Titan Company Ltd.,Consumer Durables,EQ,INE280A01028
1,INDUSINDBK,820.00,848.70,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67,IndusInd Bank Ltd.,Financial Services,EQ,INE095A01012
2,SBILIFE,1833.30,1860.40,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42,SBI Life Insurance Company Ltd.,Financial Services,EQ,INE123W01016
3,MARUTI,12400.00,12577.00,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49,Maruti Suzuki India Ltd.,Automobile and Auto Components,EQ,INE585B01010
4,COALINDIA,376.00,380.70,374.50,374.70,379.80,-,5.10,1.36,"68,46,687",258.48,543.55,349.25,-1.71,-27.65,Coal India Ltd.,Oil Gas & Consumable Fuels,EQ,INE522F01014
5,TRENT,5245.00,5356.00,5200.00,5249.00,5320.00,-,71.00,1.35,"9,76,873",517.66,"8,345.00","4,488.00",-2.54,-3.99,Trent Ltd.,Consumer Services,EQ,INE849A01020
6,EICHERMOT,5625.00,5690.00,5584.50,5621.00,5684.00,-,63.00,1.12,"4,58,305",258.62,"5,906.50","4,508.75",0.92,20.19,Eicher Motors Ltd.,Automobile and Auto Components,EQ,INE066A01021
7,BHARTIARTL,1920.00,1937.60,1912.10,1914.60,1930.30,-,15.70,0.82,"51,67,672",996.80,"2,045.80","1,422.60",-4.23,29.32,Bharti Airtel Ltd.,Telecommunication,EQ,INE397D01024
8,BAJFINANCE,889.00,893.60,882.40,885.30,892.30,-,7.00,0.79,"44,46,791",395.12,978.80,642.50,-3.61,-86.74,Bajaj Finance Ltd.,Financial Services,EQ,INE296A01032
9,SHRIRAMFIN,630.50,633.20,621.15,624.90,629.00,-,4.10,0.66,"39,96,694",250.53,730.45,493.35,-6.81,-78.94,Shriram Finance Ltd.,Financial Services,EQ,INE721A01047
10,SBIN,798.00,804.05,796.30,795.70,800.50,-,4.80,0.60,"73,81,537",590.66,875.45,680.00,-1.39,-5.57,State Bank of India,Financial Services,EQ,INE062A01020
11,ULTRACEMCO,12330.00,12378.00,12262.00,12257.00,12327.00,-,70.00,0.57,"2,67,535",329.22,"12,714.00","10,047.85",-1.66,4.53,UltraTech Cement Ltd.,Construction Materials,EQ,INE481G01011
12,TECHM,1470.10,1487.80,1461.20,1475.00,1483.00,-,8.00,0.54,"29,29,677",433.47,"1,807.70","1,209.40",-10.26,-1.48,Tech Mahindra Ltd.,Information Technology,EQ,INE669C01036
13,LT,3630.00,3657.70,3608.30,3631.10,3650.00,-,18.90,0.52,"11,58,433",421.41,"3,963.50","2,965.30",1.61,-0.36,Larsen & Toubro Ltd.,Construction,EQ,INE018A01030
14,NTPC,332.45,334.35,331.30,332.00,333.65,-,1.65,0.50,"98,55,535",327.87,448.45,292.80,-0.57,-20.51,NTPC Ltd.,Power,EQ,INE733E01010
15,HCLTECH,1479.90,1485.40,1471.20,1474.40,1480.90,-,6.50,0.44,"26,14,394",387.00,"2,012.20","1,302.75",-14.09,-7.87,HCL Technologies Ltd.,Information Technology,EQ,INE860A01027
16,BAJAJFINSV,1930.10,1942.70,1916.00,1933.60,1942.00,-,8.40,0.43,"11,01,680",212.27,"2,135.00","1,523.25",-2.76,19.46,Bajaj Finserv Ltd.,Financial Services,EQ,INE918I01026
17,BAJAJ-AUTO,8176.00,8236.50,8130.00,8187.50,8221.00,-,33.50,0.41,"1,94,083",158.91,"12,774.00","7,089.35",-2.40,-14.41,Bajaj Auto Ltd.,Automobile and Auto Components,EQ,INE917I01010
18,M&M,3195.00,3222.00,3170.10,3200.20,3213.00,-,12.80,0.40,"18,05,644",577.58,"3,303.00","2,425.00",1.57,16.82,Mahindra & Mahindra Ltd.,Automobile and Auto Components,EQ,INE101A01026
19,KOTAKBANK,2008.00,2008.00,1994.80,1997.00,2004.00,-,7.00,0.35,"24,21,332",484.58,"2,301.90","1,679.05",-5.95,11.06,Kotak Mahindra Bank Ltd.,Financial Services,EQ,INE237A01028
20,AXISBANK,1068.00,1079.90,1062.50,1068.60,1071.10,-,2.50,0.23,"53,18,081",569.76,"1,281.65",933.50,-9.07,-7.76,Axis Bank Ltd.,Financial Services,EQ,INE238A01034
21,TATAMOTORS,655.95,658.90,650.55,653.60,655.00,-,1.40,0.21,"67,14,804",439.25,"1,142.00",535.75,-5.00,-40.31,Tata Motors Ltd.,Automobile and Auto Components,EQ,INE155A01022
22,GRASIM,2799.00,2824.90,2784.70,2787.80,2792.70,-,4.90,0.18,"7,82,631",219.26,"2,896.00","2,276.95",-0.31,3.34,Grasim Industries Ltd.,Construction Materials,EQ,INE047A01021
23,HEROMOTOCO,4536.00,4581.50,4515.90,4535.90,4540.00,-,4.10,0.09,"8,03,505",365.86,"6,246.25","3,344.00",4.64,-13.79,Hero MotoCorp Ltd.,Automobile and Auto Components,EQ,INE158A01026
24,TATASTEEL,159.56,160.14,158.28,159.56,159.45,-,-0.11,-0.07,"1,44,41,034",230.16,170.18,122.62,-2.08,0.88,Tata Steel Ltd.,Metals & Mining,EQ,INE081A01020
25,JSWSTEEL,1059.00,1063.40,1048.70,1055.90,1054.10,-,-1.80,-0.17,"15,24,968",160.62,"1,074.90",854.15,1.15,17.10,JSW Steel Ltd.,Metals & Mining,EQ,INE019A01038
26,ONGC,235.50,236.00,233.05,234.83,234.30,-,-0.53,-0.23,"95,62,689",224.06,345.00,205.00,-4.39,-28.97,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,EQ,INE213A01029
27,WIPRO,246.05,246.95,244.53,246.05,245.45,-,-0.60,-0.24,"73,83,968",181.33,324.60,228.00,-8.94,-51.03,Wipro Ltd.,Information Technology,EQ,INE075A01022
28,HINDALCO,692.00,692.00,682.15,687.70,685.85,-,-1.85,-0.27,"33,02,614",226.85,772.65,546.45,-1.77,6.03,Hindalco Industries Ltd.,Metals & Mining,EQ,INE038A01020
29,HDFCLIFE,735.80,742.25,731.65,739.80,737.65,-,-2.15,-0.29,"19,88,095",146.37,820.75,584.30,-5.94,4.40,HDFC Life Insurance Company Ltd.,Financial Services,EQ,INE795G01014
30,JIOFIN,334.45,338.60,331.50,333.90,332.60,-,-1.30,-0.39,"1,60,52,991",537.41,363.00,198.65,2.43,2.02,Jio Financial Services Ltd.,Financial Services,EQ,INE758E01017
31,HINDUNILVR,2537.50,2553.00,2517.30,2543.70,2532.40,-,-11.30,-0.44,"7,56,361",191.37,"3,035.00","2,136.00",8.35,-5.86,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,EQ,INE030A01027
32,TCS,3074.40,3077.50,3042.00,3074.40,3060.00,-,-14.40,-0.47,"19,27,996",589.57,"4,592.25","2,991.60",-10.41,-28.46,Tata Consultancy Services Ltd.,Information Technology,EQ,INE467B01029
33,HDFCBANK,1986.50,1994.40,1965.50,1992.00,1981.00,-,-11.00,-0.55,"1,19,89,029","2,368.55","2,037.70","1,593.30",-0.59,19.19,HDFC Bank Ltd.,Financial Services,EQ,INE040A01034
34,NESTLEIND,2279.70,2282.40,2250.10,2277.40,2264.20,-,-13.20,-0.58,"5,67,967",128.49,"2,778.00","2,110.00",-5.24,-9.13,Nestle India Ltd.,Fast Moving Consumer Goods,EQ,INE239A01024
35,SUNPHARMA,1640.90,1644.60,1620.10,1641.60,1631.90,-,-9.70,-0.59,"16,22,897",264.48,"1,960.35","1,553.05",-2.64,-5.75,Sun Pharmaceutical Industries Ltd.,Healthcare,EQ,INE044A01036
36,ASIANPAINT,2461.90,2463.70,2409.10,2449.80,2434.90,-,-14.90,-0.61,"6,59,094",160.35,"3,394.90","2,124.75",0.52,-21.56,Asian Paints Ltd.,Consumer Durables,EQ,INE021A01026
37,APOLLOHOSP,7312.00,7342.00,7235.50,7308.00,7260.00,-,-48.00,-0.66,"2,82,791",205.90,"7,635.00","6,001.00",-3.70,8.40,Apollo Hospitals Enterprise Ltd.,Healthcare,EQ,INE437A01024
38,TATACONSUM,1072.60,1073.00,1059.10,1072.60,1065.50,-,-7.10,-0.66,"8,61,402",91.65,"1,234.30",882.90,-2.30,-10.81,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,EQ,INE192A01025
39,POWERGRID,287.10,288.65,285.10,287.95,285.90,-,-2.05,-0.71,"1,55,61,914",445.79,366.25,247.30,-2.72,-20.17,Power Grid Corporation of India Ltd.,Power,EQ,INE752E01010
40,ITC,417.20,417.95,413.00,416.85,413.80,-,-3.05,-0.73,"84,95,104",351.98,528.50,390.15,0.39,-15.32,ITC Ltd.,Fast Moving Consumer Goods,EQ,INE154A01025
41,BEL,390.00,390.25,383.35,389.55,386.60,-,-2.95,-0.76,"1,34,82,710",520.50,436.00,240.25,-9.57,27.63,Bharat Electronics Ltd.,Capital Goods,EQ,INE263A01024
42,DRREDDY,1225.00,1232.00,1205.00,1225.00,1214.40,-,-10.60,-0.87,"9,56,582",116.23,"1,421.49","1,020.00",-7.08,-82.56,Dr. Reddy's Laboratories Ltd.,Healthcare,EQ,INE089A01031
43,ETERNAL,306.90,307.60,301.70,305.25,301.95,-,-3.30,-1.08,"1,48,20,256",449.69,314.45,194.80,15.59,-,Eternal Ltd.,Consumer Services,EQ,INE758T01015
44,ICICIBANK,1453.00,1461.50,1441.00,1463.20,1445.00,-,-18.20,-1.24,"1,47,99,343","2,139.63","1,500.00","1,153.00",0.11,20.71,ICICI Bank Ltd.,Financial Services,EQ,INE090A01021
45,CIPLA,1513.50,1517.30,1491.10,1515.10,1496.30,-,-18.80,-1.24,"11,56,528",173.61,"1,702.05","1,335.00",-0.89,-1.90,Cipla Ltd.,Healthcare,EQ,INE059A01026
46,ADANIENT,2370.00,2370.00,2316.00,2363.60,2333.00,-,-30.60,-1.29,"5,76,742",134.58,"3,242.65","2,025.00",-10.42,-26.34,Adani Enterprises Ltd.,Metals & Mining,EQ,INE423A01024
47,INFY,1478.70,1478.70,1455.00,1480.50,1460.00,-,-20.50,-1.38,"1,02,13,323","1,492.22","2,006.45","1,307.00",-11.00,-19.82,Infosys Ltd.,Information Technology,EQ,INE009A01021
48,RELIANCE,1411.00,1411.00,1388.10,1411.50,1390.00,-,-21.50,-1.52,"93,15,972","1,299.11","1,551.00","1,114.85",-8.88,-53.59,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,EQ,INE002A01018
49,ADANIPORTS,1392.00,1394.20,1346.00,1388.90,1361.90,-,-27.00,-1.94,"30,00,067",411.57,"1,563.45",995.65,-4.65,-14.48,Adani Ports and Special Economic Zone Ltd.,Services,EQ,INE742F01042

In [ ]:
nifty_merge.columns

Index(['Symbol', 'Open', 'High', 'Low', 'Prev. Close', 'Ltp',
       'Indicative Close', 'Chng', '%Chng', 'Volume', 'Value', '52W H',
       '52W L', '30 D   %Chng', '365 D % Chng  02-Aug-2024', 'Company Name',
       'Industry', 'Series', 'ISIN Code'],
      dtype='object')

In [ ]:
nifty50.head()

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024
Symbol,,,,,,,,,,,,,,
NIFTY 50,24720.25,24733.1,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28
TITAN,3356.30,3443.0,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28
INDUSINDBK,820.00,848.7,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67
SBILIFE,1833.30,1860.4,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42
MARUTI,12400.00,12577.0,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49

In [ ]:
nifty_merge = nifty50.merge(nifty_sector,right_on='Symbol',how='inner') #must pass left_index
nifty_merge.shape

MergeError: Must pass "left_on" OR "left_index".

In [ ]:
nifty_sector.columns
nifty_sector=nifty_sector.set_index('Symbol')
nifty_sector

,Company Name,Industry,Series,ISIN Code
Symbol,,,,
ADANIENT,Adani Enterprises Ltd.,Metals & Mining,EQ,INE423A01024
ADANIPORTS,Adani Ports and Special Economic Zone Ltd.,Services,EQ,INE742F01042
APOLLOHOSP,Apollo Hospitals Enterprise Ltd.,Healthcare,EQ,INE437A01024
ASIANPAINT,Asian Paints Ltd.,Consumer Durables,EQ,INE021A01026
AXISBANK,Axis Bank Ltd.,Financial Services,EQ,INE238A01034
BAJAJ-AUTO,Bajaj Auto Ltd.,Automobile and Auto Components,EQ,INE917I01010
BAJFINANCE,Bajaj Finance Ltd.,Financial Services,EQ,INE296A01032
BAJAJFINSV,Bajaj Finserv Ltd.,Financial Services,EQ,INE918I01026
BEL,Bharat Electronics Ltd.,Capital Goods,EQ,INE263A01024
BHARTIARTL,Bharti Airtel Ltd.,Telecommunication,EQ,INE397D01024
CIPLA,Cipla Ltd.,Healthcare,EQ,INE059A01026
COALINDIA,Coal India Ltd.,Oil Gas & Consumable Fuels,EQ,INE522F01014
DRREDDY,Dr. Reddy's Laboratories Ltd.,Healthcare,EQ,INE089A01031
EICHERMOT,Eicher Motors Ltd.,Automobile and Auto Components,EQ,INE066A01021
ETERNAL,Eternal Ltd.,Consumer Services,EQ,INE758T01015
GRASIM,Grasim Industries Ltd.,Construction Materials,EQ,INE047A01021
HCLTECH,HCL Technologies Ltd.,Information Technology,EQ,INE860A01027
HDFCBANK,HDFC Bank Ltd.,Financial Services,EQ,INE040A01034
HDFCLIFE,HDFC Life Insurance Company Ltd.,Financial Services,EQ,INE795G01014
HEROMOTOCO,Hero MotoCorp Ltd.,Automobile and Auto Components,EQ,INE158A01026
HINDALCO,Hindalco Industries Ltd.,Metals & Mining,EQ,INE038A01020
HINDUNILVR,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,EQ,INE030A01027
ICICIBANK,ICICI Bank Ltd.,Financial Services,EQ,INE090A01021
ITC,ITC Ltd.,Fast Moving Consumer Goods,EQ,INE154A01025
INDUSINDBK,IndusInd Bank Ltd.,Financial Services,EQ,INE095A01012
INFY,Infosys Ltd.,Information Technology,EQ,INE009A01021
JSWSTEEL,JSW Steel Ltd.,Metals & Mining,EQ,INE019A01038
JIOFIN,Jio Financial Services Ltd.,Financial Services,EQ,INE758E01017
KOTAKBANK,Kotak Mahindra Bank Ltd.,Financial Services,EQ,INE237A01028
LT,Larsen & Toubro Ltd.,Construction,EQ,INE018A01030
M&M,Mahindra & Mahindra Ltd.,Automobile and Auto Components,EQ,INE101A01026
MARUTI,Maruti Suzuki India Ltd.,Automobile and Auto Components,EQ,INE585B01010
NTPC,NTPC Ltd.,Power,EQ,INE733E01010
NESTLEIND,Nestle India Ltd.,Fast Moving Consumer Goods,EQ,INE239A01024
ONGC,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,EQ,INE213A01029
POWERGRID,Power Grid Corporation of India Ltd.,Power,EQ,INE752E01010
RELIANCE,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,EQ,INE002A01018
SBILIFE,SBI Life Insurance Company Ltd.,Financial Services,EQ,INE123W01016
SHRIRAMFIN,Shriram Finance Ltd.,Financial Services,EQ,INE721A01047
SBIN,State Bank of India,Financial Services,EQ,INE062A01020
SUNPHARMA,Sun Pharmaceutical Industries Ltd.,Healthcare,EQ,INE044A01036
TCS,Tata Consultancy Services Ltd.,Information Technology,EQ,INE467B01029
TATACONSUM,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,EQ,INE192A01025
TATAMOTORS,Tata Motors Ltd.,Automobile and Auto Components,EQ,INE155A01022
TATASTEEL,Tata Steel Ltd.,Metals & Mining,EQ,INE081A01020
TECHM,Tech Mahindra Ltd.,Information Technology,EQ,INE669C01036
TITAN,Titan Company Ltd.,Consumer Durables,EQ,INE280A01028
TRENT,Trent Ltd.,Consumer Services,EQ,INE849A01020
ULTRACEMCO,UltraTech Cement Ltd.,Construction Materials,EQ,INE481G01011
WIPRO,Wipro Ltd.,Information Technology,EQ,INE075A01022

In [ ]:
nifty_merge=nifty50.merge(nifty_sector,left_index=True,right_index=True)#index on both sides
nifty_merge

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024,Company Name,Industry,Series,ISIN Code
Symbol,,,,,,,,,,,,,,,,,,
TITAN,3356.30,3443.00,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28,Titan Company Ltd.,Consumer Durables,EQ,INE280A01028
INDUSINDBK,820.00,848.70,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67,IndusInd Bank Ltd.,Financial Services,EQ,INE095A01012
SBILIFE,1833.30,1860.40,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42,SBI Life Insurance Company Ltd.,Financial Services,EQ,INE123W01016
MARUTI,12400.00,12577.00,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49,Maruti Suzuki India Ltd.,Automobile and Auto Components,EQ,INE585B01010
COALINDIA,376.00,380.70,374.50,374.70,379.80,-,5.10,1.36,"68,46,687",258.48,543.55,349.25,-1.71,-27.65,Coal India Ltd.,Oil Gas & Consumable Fuels,EQ,INE522F01014
TRENT,5245.00,5356.00,5200.00,5249.00,5320.00,-,71.00,1.35,"9,76,873",517.66,"8,345.00","4,488.00",-2.54,-3.99,Trent Ltd.,Consumer Services,EQ,INE849A01020
EICHERMOT,5625.00,5690.00,5584.50,5621.00,5684.00,-,63.00,1.12,"4,58,305",258.62,"5,906.50","4,508.75",0.92,20.19,Eicher Motors Ltd.,Automobile and Auto Components,EQ,INE066A01021
BHARTIARTL,1920.00,1937.60,1912.10,1914.60,1930.30,-,15.70,0.82,"51,67,672",996.80,"2,045.80","1,422.60",-4.23,29.32,Bharti Airtel Ltd.,Telecommunication,EQ,INE397D01024
BAJFINANCE,889.00,893.60,882.40,885.30,892.30,-,7.00,0.79,"44,46,791",395.12,978.80,642.50,-3.61,-86.74,Bajaj Finance Ltd.,Financial Services,EQ,INE296A01032
SHRIRAMFIN,630.50,633.20,621.15,624.90,629.00,-,4.10,0.66,"39,96,694",250.53,730.45,493.35,-6.81,-78.94,Shriram Finance Ltd.,Financial Services,EQ,INE721A01047
SBIN,798.00,804.05,796.30,795.70,800.50,-,4.80,0.60,"73,81,537",590.66,875.45,680.00,-1.39,-5.57,State Bank of India,Financial Services,EQ,INE062A01020
ULTRACEMCO,12330.00,12378.00,12262.00,12257.00,12327.00,-,70.00,0.57,"2,67,535",329.22,"12,714.00","10,047.85",-1.66,4.53,UltraTech Cement Ltd.,Construction Materials,EQ,INE481G01011
TECHM,1470.10,1487.80,1461.20,1475.00,1483.00,-,8.00,0.54,"29,29,677",433.47,"1,807.70","1,209.40",-10.26,-1.48,Tech Mahindra Ltd.,Information Technology,EQ,INE669C01036
LT,3630.00,3657.70,3608.30,3631.10,3650.00,-,18.90,0.52,"11,58,433",421.41,"3,963.50","2,965.30",1.61,-0.36,Larsen & Toubro Ltd.,Construction,EQ,INE018A01030
NTPC,332.45,334.35,331.30,332.00,333.65,-,1.65,0.50,"98,55,535",327.87,448.45,292.80,-0.57,-20.51,NTPC Ltd.,Power,EQ,INE733E01010
HCLTECH,1479.90,1485.40,1471.20,1474.40,1480.90,-,6.50,0.44,"26,14,394",387.00,"2,012.20","1,302.75",-14.09,-7.87,HCL Technologies Ltd.,Information Technology,EQ,INE860A01027
BAJAJFINSV,1930.10,1942.70,1916.00,1933.60,1942.00,-,8.40,0.43,"11,01,680",212.27,"2,135.00","1,523.25",-2.76,19.46,Bajaj Finserv Ltd.,Financial Services,EQ,INE918I01026
BAJAJ-AUTO,8176.00,8236.50,8130.00,8187.50,8221.00,-,33.50,0.41,"1,94,083",158.91,"12,774.00","7,089.35",-2.40,-14.41,Bajaj Auto Ltd.,Automobile and Auto Components,EQ,INE917I01010
M&M,3195.00,3222.00,3170.10,3200.20,3213.00,-,12.80,0.40,"18,05,644",577.58,"3,303.00","2,425.00",1.57,16.82,Mahindra & Mahindra Ltd.,Automobile and Auto Components,EQ,INE101A01026
KOTAKBANK,2008.00,2008.00,1994.80,1997.00,2004.00,-,7.00,0.35,"24,21,332",484.58,"2,301.90","1,679.05",-5.95,11.06,Kotak Mahindra Bank Ltd.,Financial Services,EQ,INE237A01028
AXISBANK,1068.00,1079.90,1062.50,1068.60,1071.10,-,2.50,0.23,"53,18,081",569.76,"1,281.65",933.50,-9.07,-7.76,Axis Bank Ltd.,Financial Services,EQ,INE238A01034
TATAMOTORS,655.95,658.90,650.55,653.60,655.00,-,1.40,0.21,"67,14,804",439.25,"1,142.00",535.75,-5.00,-40.31,Tata Motors Ltd.,Automobile and Auto Components,EQ,INE155A01022
GRASIM,2799.00,2824.90,2784.70,2787.80,2792.70,-,4.90,0.18,"7,82,631",219.26,"2,896.00","2,276.95",-0.31,3.34,Grasim Industries Ltd.,Construction Materials,EQ,INE047A01021
HEROMOTOCO,4536.00,4581.50,4515.90,4535.90,4540.00,-,4.10,0.09,"8,03,505",365.86,"6,246.25","3,344.00",4.64,-13.79,Hero MotoCorp Ltd.,Automobile and Auto Components,EQ,INE158A01026
TATASTEEL,159.56,160.14,158.28,159.56,159.45,-,-0.11,-0.07,"1,44,41,034",230.16,170.18,122.62,-2.08,0.88,Tata Steel Ltd.,Metals & Mining,EQ,INE081A01020
JSWSTEEL,1059.00,1063.40,1048.70,1055.90,1054.10,-,-1.80,-0.17,"15,24,968",160.62,"1,074.90",854.15,1.15,17.10,JSW Steel Ltd.,Metals & Mining,EQ,INE019A01038
ONGC,235.50,236.00,233.05,234.83,234.30,-,-0.53,-0.23,"95,62,689",224.06,345.00,205.00,-4.39,-28.97,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,EQ,INE213A01029
WIPRO,246.05,246.95,244.53,246.05,245.45,-,-0.60,-0.24,"73,83,968",181.33,324.60,228.00,-8.94,-51.03,Wipro Ltd.,Information Technology,EQ,INE075A01022
HINDALCO,692.00,692.00,682.15,687.70,685.85,-,-1.85,-0.27,"33,02,614",226.85,772.65,546.45,-1.77,6.03,Hindalco Industries Ltd.,Metals & Mining,EQ,INE038A01020
HDFCLIFE,735.80,742.25,731.65,739.80,737.65,-,-2.15,-0.29,"19,88,095",146.37,820.75,584.30,-5.94,4.40,HDFC Life Insurance Company Ltd.,Financial Services,EQ,INE795G01014
JIOFIN,334.45,338.60,331.50,333.90,332.60,-,-1.30,-0.39,"1,60,52,991",537.41,363.00,198.65,2.43,2.02,Jio Financial Services Ltd.,Financial Services,EQ,INE758E01017
HINDUNILVR,2537.50,2553.00,2517.30,2543.70,2532.40,-,-11.30,-0.44,"7,56,361",191.37,"3,035.00","2,136.00",8.35,-5.86,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,EQ,INE030A01027
TCS,3074.40,3077.50,3042.00,3074.40,3060.00,-,-14.40,-0.47,"19,27,996",589.57,"4,592.25","2,991.60",-10.41,-28.46,Tata Consultancy Services Ltd.,Information Technology,EQ,INE467B01029
HDFCBANK,1986.50,1994.40,1965.50,1992.00,1981.00,-,-11.00,-0.55,"1,19,89,029","2,368.55","2,037.70","1,593.30",-0.59,19.19,HDFC Bank Ltd.,Financial Services,EQ,INE040A01034
NESTLEIND,2279.70,2282.40,2250.10,2277.40,2264.20,-,-13.20,-0.58,"5,67,967",128.49,"2,778.00","2,110.00",-5.24,-9.13,Nestle India Ltd.,Fast Moving Consumer Goods,EQ,INE239A01024
SUNPHARMA,1640.90,1644.60,1620.10,1641.60,1631.90,-,-9.70,-0.59,"16,22,897",264.48,"1,960.35","1,553.05",-2.64,-5.75,Sun Pharmaceutical Industries Ltd.,Healthcare,EQ,INE044A01036
ASIANPAINT,2461.90,2463.70,2409.10,2449.80,2434.90,-,-14.90,-0.61,"6,59,094",160.35,"3,394.90","2,124.75",0.52,-21.56,Asian Paints Ltd.,Consumer Durables,EQ,INE021A01026
APOLLOHOSP,7312.00,7342.00,7235.50,7308.00,7260.00,-,-48.00,-0.66,"2,82,791",205.90,"7,635.00","6,001.00",-3.70,8.40,Apollo Hospitals Enterprise Ltd.,Healthcare,EQ,INE437A01024
TATACONSUM,1072.60,1073.00,1059.10,1072.60,1065.50,-,-7.10,-0.66,"8,61,402",91.65,"1,234.30",882.90,-2.30,-10.81,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,EQ,INE192A01025
POWERGRID,287.10,288.65,285.10,287.95,285.90,-,-2.05,-0.71,"1,55,61,914",445.79,366.25,247.30,-2.72,-20.17,Power Grid Corporation of India Ltd.,Power,EQ,INE752E01010
ITC,417.20,417.95,413.00,416.85,413.80,-,-3.05,-0.73,"84,95,104",351.98,528.50,390.15,0.39,-15.32,ITC Ltd.,Fast Moving Consumer Goods,EQ,INE154A01025
BEL,390.00,390.25,383.35,389.55,386.60,-,-2.95,-0.76,"1,34,82,710",520.50,436.00,240.25,-9.57,27.63,Bharat Electronics Ltd.,Capital Goods,EQ,INE263A01024
DRREDDY,1225.00,1232.00,1205.00,1225.00,1214.40,-,-10.60,-0.87,"9,56,582",116.23,"1,421.49","1,020.00",-7.08,-82.56,Dr. Reddy's Laboratories Ltd.,Healthcare,EQ,INE089A01031
ETERNAL,306.90,307.60,301.70,305.25,301.95,-,-3.30,-1.08,"1,48,20,256",449.69,314.45,194.80,15.59,-,Eternal Ltd.,Consumer Services,EQ,INE758T01015
ICICIBANK,1453.00,1461.50,1441.00,1463.20,1445.00,-,-18.20,-1.24,"1,47,99,343","2,139.63","1,500.00","1,153.00",0.11,20.71,ICICI Bank Ltd.,Financial Services,EQ,INE090A01021
CIPLA,1513.50,1517.30,1491.10,1515.10,1496.30,-,-18.80,-1.24,"11,56,528",173.61,"1,702.05","1,335.00",-0.89,-1.90,Cipla Ltd.,Healthcare,EQ,INE059A01026
ADANIENT,2370.00,2370.00,2316.00,2363.60,2333.00,-,-30.60,-1.29,"5,76,742",134.58,"3,242.65","2,025.00",-10.42,-26.34,Adani Enterprises Ltd.,Metals & Mining,EQ,INE423A01024
INFY,1478.70,1478.70,1455.00,1480.50,1460.00,-,-20.50,-1.38,"1,02,13,323","1,492.22","2,006.45","1,307.00",-11.00,-19.82,Infosys Ltd.,Information Technology,EQ,INE009A01021
RELIANCE,1411.00,1411.00,1388.10,1411.50,1390.00,-,-21.50,-1.52,"93,15,972","1,299.11","1,551.00","1,114.85",-8.88,-53.59,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,EQ,INE002A01018
ADANIPORTS,1392.00,1394.20,1346.00,1388.90,1361.90,-,-27.00,-1.94,"30,00,067",411.57,"1,563.45",995.65,-4.65,-14.48,Adani Ports and Special Economic Zone Ltd.,Services,EQ,INE742F01042

In [ ]:
nifty_join=nifty50.join(nifty_sector) #join works on  indexes
nifty_join

,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024,Company Name,Industry,Series,ISIN Code
Symbol,,,,,,,,,,,,,,,,,,
NIFTY 50,24720.25,24733.10,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28,NaN,NaN,NaN,NaN
TITAN,3356.30,3443.00,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28,Titan Company Ltd.,Consumer Durables,EQ,INE280A01028
INDUSINDBK,820.00,848.70,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67,IndusInd Bank Ltd.,Financial Services,EQ,INE095A01012
SBILIFE,1833.30,1860.40,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42,SBI Life Insurance Company Ltd.,Financial Services,EQ,INE123W01016
MARUTI,12400.00,12577.00,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49,Maruti Suzuki India Ltd.,Automobile and Auto Components,EQ,INE585B01010
COALINDIA,376.00,380.70,374.50,374.70,379.80,-,5.10,1.36,"68,46,687",258.48,543.55,349.25,-1.71,-27.65,Coal India Ltd.,Oil Gas & Consumable Fuels,EQ,INE522F01014
TRENT,5245.00,5356.00,5200.00,5249.00,5320.00,-,71.00,1.35,"9,76,873",517.66,"8,345.00","4,488.00",-2.54,-3.99,Trent Ltd.,Consumer Services,EQ,INE849A01020
EICHERMOT,5625.00,5690.00,5584.50,5621.00,5684.00,-,63.00,1.12,"4,58,305",258.62,"5,906.50","4,508.75",0.92,20.19,Eicher Motors Ltd.,Automobile and Auto Components,EQ,INE066A01021
BHARTIARTL,1920.00,1937.60,1912.10,1914.60,1930.30,-,15.70,0.82,"51,67,672",996.80,"2,045.80","1,422.60",-4.23,29.32,Bharti Airtel Ltd.,Telecommunication,EQ,INE397D01024
BAJFINANCE,889.00,893.60,882.40,885.30,892.30,-,7.00,0.79,"44,46,791",395.12,978.80,642.50,-3.61,-86.74,Bajaj Finance Ltd.,Financial Services,EQ,INE296A01032
SHRIRAMFIN,630.50,633.20,621.15,624.90,629.00,-,4.10,0.66,"39,96,694",250.53,730.45,493.35,-6.81,-78.94,Shriram Finance Ltd.,Financial Services,EQ,INE721A01047
SBIN,798.00,804.05,796.30,795.70,800.50,-,4.80,0.60,"73,81,537",590.66,875.45,680.00,-1.39,-5.57,State Bank of India,Financial Services,EQ,INE062A01020
ULTRACEMCO,12330.00,12378.00,12262.00,12257.00,12327.00,-,70.00,0.57,"2,67,535",329.22,"12,714.00","10,047.85",-1.66,4.53,UltraTech Cement Ltd.,Construction Materials,EQ,INE481G01011
TECHM,1470.10,1487.80,1461.20,1475.00,1483.00,-,8.00,0.54,"29,29,677",433.47,"1,807.70","1,209.40",-10.26,-1.48,Tech Mahindra Ltd.,Information Technology,EQ,INE669C01036
LT,3630.00,3657.70,3608.30,3631.10,3650.00,-,18.90,0.52,"11,58,433",421.41,"3,963.50","2,965.30",1.61,-0.36,Larsen & Toubro Ltd.,Construction,EQ,INE018A01030
NTPC,332.45,334.35,331.30,332.00,333.65,-,1.65,0.50,"98,55,535",327.87,448.45,292.80,-0.57,-20.51,NTPC Ltd.,Power,EQ,INE733E01010
HCLTECH,1479.90,1485.40,1471.20,1474.40,1480.90,-,6.50,0.44,"26,14,394",387.00,"2,012.20","1,302.75",-14.09,-7.87,HCL Technologies Ltd.,Information Technology,EQ,INE860A01027
BAJAJFINSV,1930.10,1942.70,1916.00,1933.60,1942.00,-,8.40,0.43,"11,01,680",212.27,"2,135.00","1,523.25",-2.76,19.46,Bajaj Finserv Ltd.,Financial Services,EQ,INE918I01026
BAJAJ-AUTO,8176.00,8236.50,8130.00,8187.50,8221.00,-,33.50,0.41,"1,94,083",158.91,"12,774.00","7,089.35",-2.40,-14.41,Bajaj Auto Ltd.,Automobile and Auto Components,EQ,INE917I01010
M&M,3195.00,3222.00,3170.10,3200.20,3213.00,-,12.80,0.40,"18,05,644",577.58,"3,303.00","2,425.00",1.57,16.82,Mahindra & Mahindra Ltd.,Automobile and Auto Components,EQ,INE101A01026
KOTAKBANK,2008.00,2008.00,1994.80,1997.00,2004.00,-,7.00,0.35,"24,21,332",484.58,"2,301.90","1,679.05",-5.95,11.06,Kotak Mahindra Bank Ltd.,Financial Services,EQ,INE237A01028
AXISBANK,1068.00,1079.90,1062.50,1068.60,1071.10,-,2.50,0.23,"53,18,081",569.76,"1,281.65",933.50,-9.07,-7.76,Axis Bank Ltd.,Financial Services,EQ,INE238A01034
TATAMOTORS,655.95,658.90,650.55,653.60,655.00,-,1.40,0.21,"67,14,804",439.25,"1,142.00",535.75,-5.00,-40.31,Tata Motors Ltd.,Automobile and Auto Components,EQ,INE155A01022
GRASIM,2799.00,2824.90,2784.70,2787.80,2792.70,-,4.90,0.18,"7,82,631",219.26,"2,896.00","2,276.95",-0.31,3.34,Grasim Industries Ltd.,Construction Materials,EQ,INE047A01021
HEROMOTOCO,4536.00,4581.50,4515.90,4535.90,4540.00,-,4.10,0.09,"8,03,505",365.86,"6,246.25","3,344.00",4.64,-13.79,Hero MotoCorp Ltd.,Automobile and Auto Components,EQ,INE158A01026
TATASTEEL,159.56,160.14,158.28,159.56,159.45,-,-0.11,-0.07,"1,44,41,034",230.16,170.18,122.62,-2.08,0.88,Tata Steel Ltd.,Metals & Mining,EQ,INE081A01020
JSWSTEEL,1059.00,1063.40,1048.70,1055.90,1054.10,-,-1.80,-0.17,"15,24,968",160.62,"1,074.90",854.15,1.15,17.10,JSW Steel Ltd.,Metals & Mining,EQ,INE019A01038
ONGC,235.50,236.00,233.05,234.83,234.30,-,-0.53,-0.23,"95,62,689",224.06,345.00,205.00,-4.39,-28.97,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,EQ,INE213A01029
WIPRO,246.05,246.95,244.53,246.05,245.45,-,-0.60,-0.24,"73,83,968",181.33,324.60,228.00,-8.94,-51.03,Wipro Ltd.,Information Technology,EQ,INE075A01022
HINDALCO,692.00,692.00,682.15,687.70,685.85,-,-1.85,-0.27,"33,02,614",226.85,772.65,546.45,-1.77,6.03,Hindalco Industries Ltd.,Metals & Mining,EQ,INE038A01020
HDFCLIFE,735.80,742.25,731.65,739.80,737.65,-,-2.15,-0.29,"19,88,095",146.37,820.75,584.30,-5.94,4.40,HDFC Life Insurance Company Ltd.,Financial Services,EQ,INE795G01014
JIOFIN,334.45,338.60,331.50,333.90,332.60,-,-1.30,-0.39,"1,60,52,991",537.41,363.00,198.65,2.43,2.02,Jio Financial Services Ltd.,Financial Services,EQ,INE758E01017
HINDUNILVR,2537.50,2553.00,2517.30,2543.70,2532.40,-,-11.30,-0.44,"7,56,361",191.37,"3,035.00","2,136.00",8.35,-5.86,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,EQ,INE030A01027
TCS,3074.40,3077.50,3042.00,3074.40,3060.00,-,-14.40,-0.47,"19,27,996",589.57,"4,592.25","2,991.60",-10.41,-28.46,Tata Consultancy Services Ltd.,Information Technology,EQ,INE467B01029
HDFCBANK,1986.50,1994.40,1965.50,1992.00,1981.00,-,-11.00,-0.55,"1,19,89,029","2,368.55","2,037.70","1,593.30",-0.59,19.19,HDFC Bank Ltd.,Financial Services,EQ,INE040A01034
NESTLEIND,2279.70,2282.40,2250.10,2277.40,2264.20,-,-13.20,-0.58,"5,67,967",128.49,"2,778.00","2,110.00",-5.24,-9.13,Nestle India Ltd.,Fast Moving Consumer Goods,EQ,INE239A01024
SUNPHARMA,1640.90,1644.60,1620.10,1641.60,1631.90,-,-9.70,-0.59,"16,22,897",264.48,"1,960.35","1,553.05",-2.64,-5.75,Sun Pharmaceutical Industries Ltd.,Healthcare,EQ,INE044A01036
ASIANPAINT,2461.90,2463.70,2409.10,2449.80,2434.90,-,-14.90,-0.61,"6,59,094",160.35,"3,394.90","2,124.75",0.52,-21.56,Asian Paints Ltd.,Consumer Durables,EQ,INE021A01026
APOLLOHOSP,7312.00,7342.00,7235.50,7308.00,7260.00,-,-48.00,-0.66,"2,82,791",205.90,"7,635.00","6,001.00",-3.70,8.40,Apollo Hospitals Enterprise Ltd.,Healthcare,EQ,INE437A01024
TATACONSUM,1072.60,1073.00,1059.10,1072.60,1065.50,-,-7.10,-0.66,"8,61,402",91.65,"1,234.30",882.90,-2.30,-10.81,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,EQ,INE192A01025
POWERGRID,287.10,288.65,285.10,287.95,285.90,-,-2.05,-0.71,"1,55,61,914",445.79,366.25,247.30,-2.72,-20.17,Power Grid Corporation of India Ltd.,Power,EQ,INE752E01010
ITC,417.20,417.95,413.00,416.85,413.80,-,-3.05,-0.73,"84,95,104",351.98,528.50,390.15,0.39,-15.32,ITC Ltd.,Fast Moving Consumer Goods,EQ,INE154A01025
BEL,390.00,390.25,383.35,389.55,386.60,-,-2.95,-0.76,"1,34,82,710",520.50,436.00,240.25,-9.57,27.63,Bharat Electronics Ltd.,Capital Goods,EQ,INE263A01024
DRREDDY,1225.00,1232.00,1205.00,1225.00,1214.40,-,-10.60,-0.87,"9,56,582",116.23,"1,421.49","1,020.00",-7.08,-82.56,Dr. Reddy's Laboratories Ltd.,Healthcare,EQ,INE089A01031
ETERNAL,306.90,307.60,301.70,305.25,301.95,-,-3.30,-1.08,"1,48,20,256",449.69,314.45,194.80,15.59,-,Eternal Ltd.,Consumer Services,EQ,INE758T01015
ICICIBANK,1453.00,1461.50,1441.00,1463.20,1445.00,-,-18.20,-1.24,"1,47,99,343","2,139.63","1,500.00","1,153.00",0.11,20.71,ICICI Bank Ltd.,Financial Services,EQ,INE090A01021
CIPLA,1513.50,1517.30,1491.10,1515.10,1496.30,-,-18.80,-1.24,"11,56,528",173.61,"1,702.05","1,335.00",-0.89,-1.90,Cipla Ltd.,Healthcare,EQ,INE059A01026
ADANIENT,2370.00,2370.00,2316.00,2363.60,2333.00,-,-30.60,-1.29,"5,76,742",134.58,"3,242.65","2,025.00",-10.42,-26.34,Adani Enterprises Ltd.,Metals & Mining,EQ,INE423A01024
INFY,1478.70,1478.70,1455.00,1480.50,1460.00,-,-20.50,-1.38,"1,02,13,323","1,492.22","2,006.45","1,307.00",-11.00,-19.82,Infosys Ltd.,Information Technology,EQ,INE009A01021
RELIANCE,1411.00,1411.00,1388.10,1411.50,1390.00,-,-21.50,-1.52,"93,15,972","1,299.11","1,551.00","1,114.85",-8.88,-53.59,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,EQ,INE002A01018
ADANIPORTS,1392.00,1394.20,1346.00,1388.90,1361.90,-,-27.00,-1.94,"30,00,067",411.57,"1,563.45",995.65,-4.65,-14.48,Adani Ports and Special Economic Zone Ltd.,Services,EQ,INE742F01042

In [ ]:
nifty_sector=nifty_sector.reset_index()
nifty_sector

,Symbol,Company Name,Industry,Series,ISIN Code
0,ADANIENT,Adani Enterprises Ltd.,Metals & Mining,EQ,INE423A01024
1,ADANIPORTS,Adani Ports and Special Economic Zone Ltd.,Services,EQ,INE742F01042
2,APOLLOHOSP,Apollo Hospitals Enterprise Ltd.,Healthcare,EQ,INE437A01024
3,ASIANPAINT,Asian Paints Ltd.,Consumer Durables,EQ,INE021A01026
4,AXISBANK,Axis Bank Ltd.,Financial Services,EQ,INE238A01034
5,BAJAJ-AUTO,Bajaj Auto Ltd.,Automobile and Auto Components,EQ,INE917I01010
6,BAJFINANCE,Bajaj Finance Ltd.,Financial Services,EQ,INE296A01032
7,BAJAJFINSV,Bajaj Finserv Ltd.,Financial Services,EQ,INE918I01026
8,BEL,Bharat Electronics Ltd.,Capital Goods,EQ,INE263A01024
9,BHARTIARTL,Bharti Airtel Ltd.,Telecommunication,EQ,INE397D01024
10,CIPLA,Cipla Ltd.,Healthcare,EQ,INE059A01026
11,COALINDIA,Coal India Ltd.,Oil Gas & Consumable Fuels,EQ,INE522F01014
12,DRREDDY,Dr. Reddy's Laboratories Ltd.,Healthcare,EQ,INE089A01031
13,EICHERMOT,Eicher Motors Ltd.,Automobile and Auto Components,EQ,INE066A01021
14,ETERNAL,Eternal Ltd.,Consumer Services,EQ,INE758T01015
15,GRASIM,Grasim Industries Ltd.,Construction Materials,EQ,INE047A01021
16,HCLTECH,HCL Technologies Ltd.,Information Technology,EQ,INE860A01027
17,HDFCBANK,HDFC Bank Ltd.,Financial Services,EQ,INE040A01034
18,HDFCLIFE,HDFC Life Insurance Company Ltd.,Financial Services,EQ,INE795G01014
19,HEROMOTOCO,Hero MotoCorp Ltd.,Automobile and Auto Components,EQ,INE158A01026
20,HINDALCO,Hindalco Industries Ltd.,Metals & Mining,EQ,INE038A01020
21,HINDUNILVR,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,EQ,INE030A01027
22,ICICIBANK,ICICI Bank Ltd.,Financial Services,EQ,INE090A01021
23,ITC,ITC Ltd.,Fast Moving Consumer Goods,EQ,INE154A01025
24,INDUSINDBK,IndusInd Bank Ltd.,Financial Services,EQ,INE095A01012
25,INFY,Infosys Ltd.,Information Technology,EQ,INE009A01021
26,JSWSTEEL,JSW Steel Ltd.,Metals & Mining,EQ,INE019A01038
27,JIOFIN,Jio Financial Services Ltd.,Financial Services,EQ,INE758E01017
28,KOTAKBANK,Kotak Mahindra Bank Ltd.,Financial Services,EQ,INE237A01028
29,LT,Larsen & Toubro Ltd.,Construction,EQ,INE018A01030
30,M&M,Mahindra & Mahindra Ltd.,Automobile and Auto Components,EQ,INE101A01026
31,MARUTI,Maruti Suzuki India Ltd.,Automobile and Auto Components,EQ,INE585B01010
32,NTPC,NTPC Ltd.,Power,EQ,INE733E01010
33,NESTLEIND,Nestle India Ltd.,Fast Moving Consumer Goods,EQ,INE239A01024
34,ONGC,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,EQ,INE213A01029
35,POWERGRID,Power Grid Corporation of India Ltd.,Power,EQ,INE752E01010
36,RELIANCE,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,EQ,INE002A01018
37,SBILIFE,SBI Life Insurance Company Ltd.,Financial Services,EQ,INE123W01016
38,SHRIRAMFIN,Shriram Finance Ltd.,Financial Services,EQ,INE721A01047
39,SBIN,State Bank of India,Financial Services,EQ,INE062A01020
40,SUNPHARMA,Sun Pharmaceutical Industries Ltd.,Healthcare,EQ,INE044A01036
41,TCS,Tata Consultancy Services Ltd.,Information Technology,EQ,INE467B01029
42,TATACONSUM,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,EQ,INE192A01025
43,TATAMOTORS,Tata Motors Ltd.,Automobile and Auto Components,EQ,INE155A01022
44,TATASTEEL,Tata Steel Ltd.,Metals & Mining,EQ,INE081A01020
45,TECHM,Tech Mahindra Ltd.,Information Technology,EQ,INE669C01036
46,TITAN,Titan Company Ltd.,Consumer Durables,EQ,INE280A01028
47,TRENT,Trent Ltd.,Consumer Services,EQ,INE849A01020
48,ULTRACEMCO,UltraTech Cement Ltd.,Construction Materials,EQ,INE481G01011
49,WIPRO,Wipro Ltd.,Information Technology,EQ,INE075A01022

In [ ]:
nifty501=nifty50.reset_index()
nifty501
nifty_sector=nifty_sector.set_index('Symbol')
niftyjoin2=nifty501.join(nifty_sector,on='Symbol')#on is column on left df, not right one
niftyjoin2

,Symbol,Open,High,Low,Prev. Close,Ltp,Indicative Close,Chng,%Chng,Volume,Value,52W H,52W L,30 D %Chng,365 D % Chng 02-Aug-2024,Company Name,Industry,Series,ISIN Code
0,NIFTY 50,24720.25,24733.10,24590.30,24722.75,24649.55,-,-73.20,-0.30,"25,18,49,778","23,815.20","26,277.35","21,743.65",-3.19,-0.28,NaN,NaN,NaN,NaN
1,TITAN,3356.30,3443.00,3348.00,3356.30,3424.00,-,67.70,2.02,"8,37,335",285.13,"3,867.00","2,925.00",-7.29,-1.28,Titan Company Ltd.,Consumer Durables,EQ,INE280A01028
2,INDUSINDBK,820.00,848.70,810.05,804.05,817.40,-,13.35,1.66,"1,89,82,770","1,570.06","1,498.00",606.00,-4.33,-41.67,IndusInd Bank Ltd.,Financial Services,EQ,INE095A01012
3,SBILIFE,1833.30,1860.40,1818.70,1831.50,1860.00,-,28.50,1.56,"12,51,783",231.37,"1,936.00","1,372.55",3.18,6.42,SBI Life Insurance Company Ltd.,Financial Services,EQ,INE123W01016
4,MARUTI,12400.00,12577.00,12370.00,12365.00,12543.00,-,178.00,1.44,"2,33,560",292.25,"13,541.65","10,725.00",-0.86,-1.49,Maruti Suzuki India Ltd.,Automobile and Auto Components,EQ,INE585B01010
5,COALINDIA,376.00,380.70,374.50,374.70,379.80,-,5.10,1.36,"68,46,687",258.48,543.55,349.25,-1.71,-27.65,Coal India Ltd.,Oil Gas & Consumable Fuels,EQ,INE522F01014
6,TRENT,5245.00,5356.00,5200.00,5249.00,5320.00,-,71.00,1.35,"9,76,873",517.66,"8,345.00","4,488.00",-2.54,-3.99,Trent Ltd.,Consumer Services,EQ,INE849A01020
7,EICHERMOT,5625.00,5690.00,5584.50,5621.00,5684.00,-,63.00,1.12,"4,58,305",258.62,"5,906.50","4,508.75",0.92,20.19,Eicher Motors Ltd.,Automobile and Auto Components,EQ,INE066A01021
8,BHARTIARTL,1920.00,1937.60,1912.10,1914.60,1930.30,-,15.70,0.82,"51,67,672",996.80,"2,045.80","1,422.60",-4.23,29.32,Bharti Airtel Ltd.,Telecommunication,EQ,INE397D01024
9,BAJFINANCE,889.00,893.60,882.40,885.30,892.30,-,7.00,0.79,"44,46,791",395.12,978.80,642.50,-3.61,-86.74,Bajaj Finance Ltd.,Financial Services,EQ,INE296A01032
10,SHRIRAMFIN,630.50,633.20,621.15,624.90,629.00,-,4.10,0.66,"39,96,694",250.53,730.45,493.35,-6.81,-78.94,Shriram Finance Ltd.,Financial Services,EQ,INE721A01047
11,SBIN,798.00,804.05,796.30,795.70,800.50,-,4.80,0.60,"73,81,537",590.66,875.45,680.00,-1.39,-5.57,State Bank of India,Financial Services,EQ,INE062A01020
12,ULTRACEMCO,12330.00,12378.00,12262.00,12257.00,12327.00,-,70.00,0.57,"2,67,535",329.22,"12,714.00","10,047.85",-1.66,4.53,UltraTech Cement Ltd.,Construction Materials,EQ,INE481G01011
13,TECHM,1470.10,1487.80,1461.20,1475.00,1483.00,-,8.00,0.54,"29,29,677",433.47,"1,807.70","1,209.40",-10.26,-1.48,Tech Mahindra Ltd.,Information Technology,EQ,INE669C01036
14,LT,3630.00,3657.70,3608.30,3631.10,3650.00,-,18.90,0.52,"11,58,433",421.41,"3,963.50","2,965.30",1.61,-0.36,Larsen & Toubro Ltd.,Construction,EQ,INE018A01030
15,NTPC,332.45,334.35,331.30,332.00,333.65,-,1.65,0.50,"98,55,535",327.87,448.45,292.80,-0.57,-20.51,NTPC Ltd.,Power,EQ,INE733E01010
16,HCLTECH,1479.90,1485.40,1471.20,1474.40,1480.90,-,6.50,0.44,"26,14,394",387.00,"2,012.20","1,302.75",-14.09,-7.87,HCL Technologies Ltd.,Information Technology,EQ,INE860A01027
17,BAJAJFINSV,1930.10,1942.70,1916.00,1933.60,1942.00,-,8.40,0.43,"11,01,680",212.27,"2,135.00","1,523.25",-2.76,19.46,Bajaj Finserv Ltd.,Financial Services,EQ,INE918I01026
18,BAJAJ-AUTO,8176.00,8236.50,8130.00,8187.50,8221.00,-,33.50,0.41,"1,94,083",158.91,"12,774.00","7,089.35",-2.40,-14.41,Bajaj Auto Ltd.,Automobile and Auto Components,EQ,INE917I01010
19,M&M,3195.00,3222.00,3170.10,3200.20,3213.00,-,12.80,0.40,"18,05,644",577.58,"3,303.00","2,425.00",1.57,16.82,Mahindra & Mahindra Ltd.,Automobile and Auto Components,EQ,INE101A01026
20,KOTAKBANK,2008.00,2008.00,1994.80,1997.00,2004.00,-,7.00,0.35,"24,21,332",484.58,"2,301.90","1,679.05",-5.95,11.06,Kotak Mahindra Bank Ltd.,Financial Services,EQ,INE237A01028
21,AXISBANK,1068.00,1079.90,1062.50,1068.60,1071.10,-,2.50,0.23,"53,18,081",569.76,"1,281.65",933.50,-9.07,-7.76,Axis Bank Ltd.,Financial Services,EQ,INE238A01034
22,TATAMOTORS,655.95,658.90,650.55,653.60,655.00,-,1.40,0.21,"67,14,804",439.25,"1,142.00",535.75,-5.00,-40.31,Tata Motors Ltd.,Automobile and Auto Components,EQ,INE155A01022
23,GRASIM,2799.00,2824.90,2784.70,2787.80,2792.70,-,4.90,0.18,"7,82,631",219.26,"2,896.00","2,276.95",-0.31,3.34,Grasim Industries Ltd.,Construction Materials,EQ,INE047A01021
24,HEROMOTOCO,4536.00,4581.50,4515.90,4535.90,4540.00,-,4.10,0.09,"8,03,505",365.86,"6,246.25","3,344.00",4.64,-13.79,Hero MotoCorp Ltd.,Automobile and Auto Components,EQ,INE158A01026
25,TATASTEEL,159.56,160.14,158.28,159.56,159.45,-,-0.11,-0.07,"1,44,41,034",230.16,170.18,122.62,-2.08,0.88,Tata Steel Ltd.,Metals & Mining,EQ,INE081A01020
26,JSWSTEEL,1059.00,1063.40,1048.70,1055.90,1054.10,-,-1.80,-0.17,"15,24,968",160.62,"1,074.90",854.15,1.15,17.10,JSW Steel Ltd.,Metals & Mining,EQ,INE019A01038
27,ONGC,235.50,236.00,233.05,234.83,234.30,-,-0.53,-0.23,"95,62,689",224.06,345.00,205.00,-4.39,-28.97,Oil & Natural Gas Corporation Ltd.,Oil Gas & Consumable Fuels,EQ,INE213A01029
28,WIPRO,246.05,246.95,244.53,246.05,245.45,-,-0.60,-0.24,"73,83,968",181.33,324.60,228.00,-8.94,-51.03,Wipro Ltd.,Information Technology,EQ,INE075A01022
29,HINDALCO,692.00,692.00,682.15,687.70,685.85,-,-1.85,-0.27,"33,02,614",226.85,772.65,546.45,-1.77,6.03,Hindalco Industries Ltd.,Metals & Mining,EQ,INE038A01020
30,HDFCLIFE,735.80,742.25,731.65,739.80,737.65,-,-2.15,-0.29,"19,88,095",146.37,820.75,584.30,-5.94,4.40,HDFC Life Insurance Company Ltd.,Financial Services,EQ,INE795G01014
31,JIOFIN,334.45,338.60,331.50,333.90,332.60,-,-1.30,-0.39,"1,60,52,991",537.41,363.00,198.65,2.43,2.02,Jio Financial Services Ltd.,Financial Services,EQ,INE758E01017
32,HINDUNILVR,2537.50,2553.00,2517.30,2543.70,2532.40,-,-11.30,-0.44,"7,56,361",191.37,"3,035.00","2,136.00",8.35,-5.86,Hindustan Unilever Ltd.,Fast Moving Consumer Goods,EQ,INE030A01027
33,TCS,3074.40,3077.50,3042.00,3074.40,3060.00,-,-14.40,-0.47,"19,27,996",589.57,"4,592.25","2,991.60",-10.41,-28.46,Tata Consultancy Services Ltd.,Information Technology,EQ,INE467B01029
34,HDFCBANK,1986.50,1994.40,1965.50,1992.00,1981.00,-,-11.00,-0.55,"1,19,89,029","2,368.55","2,037.70","1,593.30",-0.59,19.19,HDFC Bank Ltd.,Financial Services,EQ,INE040A01034
35,NESTLEIND,2279.70,2282.40,2250.10,2277.40,2264.20,-,-13.20,-0.58,"5,67,967",128.49,"2,778.00","2,110.00",-5.24,-9.13,Nestle India Ltd.,Fast Moving Consumer Goods,EQ,INE239A01024
36,SUNPHARMA,1640.90,1644.60,1620.10,1641.60,1631.90,-,-9.70,-0.59,"16,22,897",264.48,"1,960.35","1,553.05",-2.64,-5.75,Sun Pharmaceutical Industries Ltd.,Healthcare,EQ,INE044A01036
37,ASIANPAINT,2461.90,2463.70,2409.10,2449.80,2434.90,-,-14.90,-0.61,"6,59,094",160.35,"3,394.90","2,124.75",0.52,-21.56,Asian Paints Ltd.,Consumer Durables,EQ,INE021A01026
38,APOLLOHOSP,7312.00,7342.00,7235.50,7308.00,7260.00,-,-48.00,-0.66,"2,82,791",205.90,"7,635.00","6,001.00",-3.70,8.40,Apollo Hospitals Enterprise Ltd.,Healthcare,EQ,INE437A01024
39,TATACONSUM,1072.60,1073.00,1059.10,1072.60,1065.50,-,-7.10,-0.66,"8,61,402",91.65,"1,234.30",882.90,-2.30,-10.81,Tata Consumer Products Ltd.,Fast Moving Consumer Goods,EQ,INE192A01025
40,POWERGRID,287.10,288.65,285.10,287.95,285.90,-,-2.05,-0.71,"1,55,61,914",445.79,366.25,247.30,-2.72,-20.17,Power Grid Corporation of India Ltd.,Power,EQ,INE752E01010
41,ITC,417.20,417.95,413.00,416.85,413.80,-,-3.05,-0.73,"84,95,104",351.98,528.50,390.15,0.39,-15.32,ITC Ltd.,Fast Moving Consumer Goods,EQ,INE154A01025
42,BEL,390.00,390.25,383.35,389.55,386.60,-,-2.95,-0.76,"1,34,82,710",520.50,436.00,240.25,-9.57,27.63,Bharat Electronics Ltd.,Capital Goods,EQ,INE263A01024
43,DRREDDY,1225.00,1232.00,1205.00,1225.00,1214.40,-,-10.60,-0.87,"9,56,582",116.23,"1,421.49","1,020.00",-7.08,-82.56,Dr. Reddy's Laboratories Ltd.,Healthcare,EQ,INE089A01031
44,ETERNAL,306.90,307.60,301.70,305.25,301.95,-,-3.30,-1.08,"1,48,20,256",449.69,314.45,194.80,15.59,-,Eternal Ltd.,Consumer Services,EQ,INE758T01015
45,ICICIBANK,1453.00,1461.50,1441.00,1463.20,1445.00,-,-18.20,-1.24,"1,47,99,343","2,139.63","1,500.00","1,153.00",0.11,20.71,ICICI Bank Ltd.,Financial Services,EQ,INE090A01021
46,CIPLA,1513.50,1517.30,1491.10,1515.10,1496.30,-,-18.80,-1.24,"11,56,528",173.61,"1,702.05","1,335.00",-0.89,-1.90,Cipla Ltd.,Healthcare,EQ,INE059A01026
47,ADANIENT,2370.00,2370.00,2316.00,2363.60,2333.00,-,-30.60,-1.29,"5,76,742",134.58,"3,242.65","2,025.00",-10.42,-26.34,Adani Enterprises Ltd.,Metals & Mining,EQ,INE423A01024
48,INFY,1478.70,1478.70,1455.00,1480.50,1460.00,-,-20.50,-1.38,"1,02,13,323","1,492.22","2,006.45","1,307.00",-11.00,-19.82,Infosys Ltd.,Information Technology,EQ,INE009A01021
49,RELIANCE,1411.00,1411.00,1388.10,1411.50,1390.00,-,-21.50,-1.52,"93,15,972","1,299.11","1,551.00","1,114.85",-8.88,-53.59,Reliance Industries Ltd.,Oil Gas & Consumable Fuels,EQ,INE002A01018
50,ADANIPORTS,1392.00,1394.20,1346.00,1388.90,1361.90,-,-27.00,-1.94,"30,00,067",411.57,"1,563.45",995.65,-4.65,-14.48,Adani Ports and Special Economic Zone Ltd.,Services,EQ,INE742F01042

In [ ]:
nifty_sector.dtypes

In [ ]:
nifty_join['Sign'] = nifty_join['%Chng'].apply(lambda x: 'Advances' if x > 0 else 'Declines' if x < 0 else 'Zero')
nifty_join['Sign'].value_counts()

In [ ]:
nifty_join.head()
print(nifty_join.columns)
nifty_industry=pd.DataFrame(nifty_join.groupby('Industry')['Company Name'].count())

In [ ]:
nifty_industry.sort_values('Company Name',ascending=False)

In [ ]:
nifty_change = nifty_join.groupby('Industry').agg({'Company Name':'count','%Chng':'median','30 D   %Chng':'mean'})

In [ ]:
nifty_change

In [ ]:
import matplotlib.pyplot as plt

# Set better default color map globally (use any name from the list above)
plt.rcParams['axes.prop_cycle'] = plt.cycler(color=plt.cm.tab10.colors)

In [ ]:
nifty_change[['%Chng','30 D   %Chng']].plot(kind='bar')

In [ ]:
nifty_change['color']='lightgreen'
nifty_change.loc[nifty_change[nifty_change['%Chng']<0].index,'color']='orange'

In [ ]:
nifty_change

In [ ]:
nifty_change['%Chng'].plot(kind='bar', color=nifty_change['color'], legend=False)

In [ ]:
nifty_change['%Chng'].idxmax()

In [ ]:
nifty_change.loc[nifty_change['%Chng'].idxmax(),'color']='green'
nifty_change.loc[nifty_change['%Chng'].idxmin(),'color']='red'

In [ ]:
nifty_change

In [ ]:
nifty_change['%Chng'].plot(kind='bar', color=nifty_change['color'], legend=False)